name: main

on: [push]
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: Gr1N/setup-poetry@v7

    - name: Check dependencies
      run: make doctor

    - uses: actions/cache@v2
      with:
        path: .venv
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      run: make install

    - name: Run bake
      run: make bake

    - name: Run template-ci
      run: make template-ci
